version: "3.9"

services:
  postgres:
    image: postgres:10.3
    restart: "always"
    environment:
      POSTGRES_USER: "wazobia"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "touchcore"
    volumes:
      - .dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
